### ISSUE TITLE
open source license? is it thought as a collaborative project?

### ISSUE THREAD

**Issue by timmwille** [evildmp/diataxis-documentation-framework#14]
maybe I missed the info somewhere, where can I find the license file/note?
Was checking if it is possible to include the concept into Open Educational Resources.

Cheers

**Comment by robredpath** [comment]
I came here just to ask this, too - I'd love to use some of the resources here in my work but without a proper license I can't. 

I'd be happy to help choose an appropriate license, if that's helpful?

**Comment by evildmp** [comment]
Hi @timmwille @robredpath. I am happy to accept corrections and also suggestions for improvement. 

It's not really a collaborative project in the way that open-source software is.

Please feel free to use/borrow/rework the material and concepts as you wish. If possible, please refer back to https://diataxis.fr.

**Comment by evildmp** [comment]
Thanks for the suggestion; implemented.

**Comment by timmwille** [comment]
I'll share it right away, good news, thx !

**Comment by jamesottaway** [comment]
@evildmp Are you aware that Divio have forked the repo and removed all reference to you and the original source?

IANAL, but their "[update to new theme](https://github.com/divio/diataxis-documentation-framework/commit/32a413767fd409e78e78324f3dd4321d6297d6f7)" commit (especially in [conf.py](https://github.com/divio/diataxis-documentation-framework/commit/32a413767fd409e78e78324f3dd4321d6297d6f7#diff-6e03d3d89630aba3403afea3514a3ac5948e70d1ced091012e56446f614da340)) could violate the CC-BY-SA license, since there's no attribution back to you.

**Comment by evildmp** [comment]
@jamesottaway Thanks for pointing it out, but it's absolutely fine! I used to work at Divio, which is where Diátaxis started life. https://documentation.divio.com has been around for years, and predates https://diataxis.fr.

**Comment by wolftune** [comment]
Super happy to have learned about the continuation of this project and the CC BY-SA licensing. I have made plans to reference these ideas in other projects and am thrilled to have this FLO (free/libre/open) reference to cite instead of Divio.

> It's not really a collaborative project in the way that open-source software is.

Is this a ramification of having some code-centric starting assumptions about FLO? Why not treat it the same way?

Many or even *most* FLO software projects are actually made by one person or one entity, some with near-zero outside collaboration. So, FLO software *also* can be not-really-collaborative as a matter of circumstance. Perhaps this can be thought of that way. It's not focused on being collaborative, but typo-fixes and other improvements and things that move more toward collaboration could still be welcomed, and just maybe some people will make significant contributions. Nothing wrong with that, right?
